import type { CommunityReview, SafetyLocation } from './safety'

// --- Mock data -------------------------------------------------------------
// Realistic placeholder data. Replace these arrays with live queries later
// (OpenStreetMap for geometry, Supabase for reviews/scores, weather API for
// day/night + lighting adjustments). Keep the shapes identical.

export const popularDestinations: SafetyLocation[] = [
  {
    id: 'chennai',
    name: 'Chennai',
    area: 'Tamil Nadu, India',
    type: 'city',
    score: 84,
    rating: 4.4,
    reviews: 1284,
    daySafety: 89,
    nightSafety: 74,
    lighting: 80,
    crowd: 86,
    policeDistanceKm: 1.2,
    hospitalDistanceKm: 2.1,
    coords: { lat: 13.0827, lng: 80.2707 },
    image: '/destinations/chennai.png',
    factors: [
      { label: 'Daytime safety', value: 89 },
      { label: 'Nighttime safety', value: 74 },
      { label: 'Street lighting', value: 80 },
      { label: 'Crowd & activity', value: 86 },
      { label: 'Emergency access', value: 82 },
    ],
  },
  {
    id: 'bengaluru',
    name: 'Bengaluru',
    area: 'Karnataka, India',
    type: 'city',
    score: 88,
    rating: 4.6,
    reviews: 2043,
    daySafety: 92,
    nightSafety: 80,
    lighting: 85,
    crowd: 90,
    policeDistanceKm: 0.9,
    hospitalDistanceKm: 1.4,
    coords: { lat: 12.9716, lng: 77.5946 },
    image: '/destinations/bengaluru.png',
    factors: [
      { label: 'Daytime safety', value: 92 },
      { label: 'Nighttime safety', value: 80 },
      { label: 'Street lighting', value: 85 },
      { label: 'Crowd & activity', value: 90 },
      { label: 'Emergency access', value: 88 },
    ],
  },
  {
    id: 'mumbai',
    name: 'Mumbai',
    area: 'Maharashtra, India',
    type: 'city',
    score: 72,
    rating: 4.1,
    reviews: 3110,
    daySafety: 84,
    nightSafety: 62,
    lighting: 70,
    crowd: 88,
    policeDistanceKm: 0.7,
    hospitalDistanceKm: 1.1,
    coords: { lat: 19.076, lng: 72.8777 },
    image: '/destinations/mumbai.png',
    factors: [
      { label: 'Daytime safety', value: 84 },
      { label: 'Nighttime safety', value: 62 },
      { label: 'Street lighting', value: 70 },
      { label: 'Crowd & activity', value: 88 },
      { label: 'Emergency access', value: 79 },
    ],
  },
  {
    id: 'goa',
    name: 'Goa',
    area: 'Goa, India',
    type: 'city',
    score: 79,
    rating: 4.3,
    reviews: 1876,
    daySafety: 86,
    nightSafety: 68,
    lighting: 66,
    crowd: 74,
    policeDistanceKm: 2.4,
    hospitalDistanceKm: 3.2,
    coords: { lat: 15.2993, lng: 74.124 },
    image: '/destinations/goa.png',
    factors: [
      { label: 'Daytime safety', value: 86 },
      { label: 'Nighttime safety', value: 68 },
      { label: 'Street lighting', value: 66 },
      { label: 'Crowd & activity', value: 74 },
      { label: 'Emergency access', value: 71 },
    ],
  },
]

// Locations plotted on the Explore map (mix of areas, hotels, hospitals, etc).
export const mapLocations: SafetyLocation[] = [
  ...popularDestinations,
  {
    id: 'marina-district',
    name: 'Marina Beach District',
    area: 'Chennai',
    type: 'landmark',
    score: 91,
    rating: 4.7,
    reviews: 512,
    daySafety: 95,
    nightSafety: 82,
    lighting: 88,
    crowd: 93,
    policeDistanceKm: 0.4,
    hospitalDistanceKm: 1.0,
    coords: { lat: 13.0500, lng: 80.2824 },
    factors: [
      { label: 'Daytime safety', value: 95 },
      { label: 'Nighttime safety', value: 82 },
      { label: 'Street lighting', value: 88 },
      { label: 'Crowd & activity', value: 93 },
      { label: 'Emergency access', value: 90 },
    ],
  },
  {
    id: 'harbour-lane',
    name: 'Old Harbour Lane',
    area: 'Mumbai',
    type: 'landmark',
    score: 46,
    rating: 3.2,
    reviews: 208,
    daySafety: 58,
    nightSafety: 32,
    lighting: 38,
    crowd: 44,
    policeDistanceKm: 3.1,
    hospitalDistanceKm: 4.0,
    coords: { lat: 18.9527, lng: 72.8342 },
    factors: [
      { label: 'Daytime safety', value: 58 },
      { label: 'Nighttime safety', value: 32 },
      { label: 'Street lighting', value: 38 },
      { label: 'Crowd & activity', value: 44 },
      { label: 'Emergency access', value: 48 },
    ],
  },
  {
    id: 'grand-park-hotel',
    name: 'The Grand Park Hotel',
    area: 'Bengaluru',
    type: 'hotel',
    score: 93,
    rating: 4.8,
    reviews: 964,
    daySafety: 96,
    nightSafety: 88,
    lighting: 92,
    crowd: 84,
    policeDistanceKm: 0.6,
    hospitalDistanceKm: 0.9,
    coords: { lat: 12.9758, lng: 77.6050 },
    factors: [
      { label: 'Daytime safety', value: 96 },
      { label: 'Nighttime safety', value: 88 },
      { label: 'Street lighting', value: 92 },
      { label: 'Crowd & activity', value: 84 },
      { label: 'Emergency access', value: 95 },
    ],
  },
  {
    id: 'riverside-market',
    name: 'Riverside Night Market',
    area: 'Goa',
    type: 'landmark',
    score: 64,
    rating: 3.9,
    reviews: 341,
    daySafety: 78,
    nightSafety: 52,
    lighting: 55,
    crowd: 70,
    policeDistanceKm: 1.9,
    hospitalDistanceKm: 2.6,
    coords: { lat: 15.5530, lng: 73.7517 },
    factors: [
      { label: 'Daytime safety', value: 78 },
      { label: 'Nighttime safety', value: 52 },
      { label: 'Street lighting', value: 55 },
      { label: 'Crowd & activity', value: 70 },
      { label: 'Emergency access', value: 60 },
    ],
  },
  {
    id: 'central-station',
    name: 'Central Station Area',
    area: 'Mumbai',
    type: 'landmark',
    score: 55,
    rating: 3.5,
    reviews: 723,
    daySafety: 70,
    nightSafety: 40,
    lighting: 48,
    crowd: 82,
    policeDistanceKm: 0.5,
    hospitalDistanceKm: 1.3,
    coords: { lat: 18.9402, lng: 72.8356 },
    factors: [
      { label: 'Daytime safety', value: 70 },
      { label: 'Nighttime safety', value: 40 },
      { label: 'Street lighting', value: 48 },
      { label: 'Crowd & activity', value: 82 },
      { label: 'Emergency access', value: 75 },
    ],
  },
  {
    id: 'city-general-hospital',
    name: 'City General Hospital',
    area: 'Chennai',
    type: 'hospital',
    score: 90,
    rating: 4.5,
    reviews: 187,
    daySafety: 94,
    nightSafety: 84,
    lighting: 90,
    crowd: 72,
    policeDistanceKm: 0.8,
    hospitalDistanceKm: 0,
    coords: { lat: 13.0770, lng: 80.2615 },
    factors: [
      { label: 'Daytime safety', value: 94 },
      { label: 'Nighttime safety', value: 84 },
      { label: 'Street lighting', value: 90 },
      { label: 'Crowd & activity', value: 72 },
      { label: 'Emergency access', value: 98 },
    ],
  },
  {
    id: 'central-police-station',
    name: 'Central Police Station',
    area: 'Bengaluru',
    type: 'police',
    score: 95,
    rating: 4.6,
    reviews: 96,
    daySafety: 97,
    nightSafety: 90,
    lighting: 93,
    crowd: 68,
    policeDistanceKm: 0,
    hospitalDistanceKm: 1.6,
    coords: { lat: 12.9773, lng: 77.5779 },
    factors: [
      { label: 'Daytime safety', value: 97 },
      { label: 'Nighttime safety', value: 90 },
      { label: 'Street lighting', value: 93 },
      { label: 'Crowd & activity', value: 68 },
      { label: 'Emergency access', value: 99 },
    ],
  },
  {
    id: 'reported-alley',
    name: 'Reported Incident · Back Alley',
    area: 'Mumbai',
    type: 'report',
    score: 38,
    rating: 2.4,
    reviews: 54,
    daySafety: 52,
    nightSafety: 24,
    lighting: 30,
    crowd: 36,
    policeDistanceKm: 2.8,
    hospitalDistanceKm: 3.5,
    coords: { lat: 19.0820, lng: 72.8845 },
    factors: [
      { label: 'Daytime safety', value: 52 },
      { label: 'Nighttime safety', value: 24 },
      { label: 'Street lighting', value: 30 },
      { label: 'Crowd & activity', value: 36 },
      { label: 'Emergency access', value: 42 },
    ],
  },
]

export const communityReviews: CommunityReview[] = [
  {
    id: 'r1',
    author: 'Ananya R.',
    initials: 'AR',
    location: 'Marina Beach District',
    rating: 5,
    timeAgo: '2 days ago',
    body: 'Felt completely safe walking here in the evening. Well lit, plenty of people around, and a police booth nearby.',
  },
  {
    id: 'r2',
    author: 'David L.',
    initials: 'DL',
    location: 'Old Harbour Lane',
    rating: 2,
    timeAgo: '5 days ago',
    body: 'Very quiet and poorly lit after dark. I would avoid this stretch at night and take the main road instead.',
  },
  {
    id: 'r3',
    author: 'Meera K.',
    initials: 'MK',
    location: 'The Grand Park Hotel',
    rating: 5,
    timeAgo: '1 week ago',
    body: 'Excellent security at the entrance and the surrounding area is calm. Hospital is a short ride away.',
  },
  {
    id: 'r4',
    author: 'Tom H.',
    initials: 'TH',
    location: 'Riverside Night Market',
    rating: 4,
    timeAgo: '1 week ago',
    body: 'Lively and fun during the day. Gets a bit crowded at night so keep an eye on your belongings.',
  },
]

export const emergencyContacts = [
  {
    id: 'police',
    label: 'Nearby Police',
    value: '100',
    detail: 'Avg. response 6 min in mapped zones',
  },
  {
    id: 'hospital',
    label: 'Nearby Hospitals',
    value: '108',
    detail: 'Ambulance & emergency medical care',
  },
  {
    id: 'assist',
    label: 'Emergency Assistance',
    value: '112',
    detail: 'All-in-one national emergency line',
  },
]
